name: Project Stats
on: 
  workflow_dispatch:

  # force workflow to showup
  push:
    tags:
      - 'v1.0.0'

jobs:
  main:
    name: 'Run'
    uses: usf-cs272n-spring2025/cs272n-bot/.github/workflows/calc-stats.yml@main
    if: ${{ github.event_name == 'workflow_dispatch' }}
    secrets: inherit
    permissions: write-all
